### ISSUE TITLE
Self-hosted JS?

### ISSUE THREAD

**Issue by hrj** [darkfrog26/hyperscala#20]
It would be good if HyperScala had an option to use self-hosted JS instead of referring to third-party hosts:
* netdna.bootstrapcdn.com
* cdnjs.cloudflare.com
* code.createjs.com
* code.jquery.com

**Comment by darkfrog26** [comment]
It supports both.  Look at EaselJS for an example of both self-hosted and third-party hosted JS.

**Comment by hrj** [comment]
Perhaps my descriptiong was not clear. I meant to suggest a flag to load the standard JS libs from self-hosted URL.

For example, in EasleJS module, a link to `https://code.createjs.com/easeljs-0.8.0.min.js` is hard-coded. Instead, it would be convenient to have a flag which chooses between that and `/js/easeljs-0.8.0.min.js`.

**Comment by darkfrog26** [comment]
Yeah, I've considered that, but then that means I have to add yet further bloat to Hyperscala by storing all of those JS dependencies in the project and I'd like to get away from that.

**Comment by hrj** [comment]
One solution:

Download the JS on the server side at run-time, and then serve it through a local path. The download can happen to an in-memory buffer (with a [soft-reference](http://docs.oracle.com/javase/7/docs/api/java/lang/ref/SoftReference.html)) and subsequent requests can be served directly from the buffer.

A nice enhancement to this would be:
Keep a MD5 checksum in the server, and verify the download before serving it.

If this sounds good in concept, I could attempt implementing it.

**Comment by darkfrog26** [comment]
Though it might worth considering at some point, this is a really low-priority issue right now.  There are far more important issues I expected you to be tackling in Hyperscala.
