### ISSUE TITLE
Dropzone events may interleave

### ISSUE THREAD

**Issue by tindzk** [darkfrog26/hyperscala#27]
It may happen that the events ``addedFileEvent`` and ``fileReceived`` are called at the same time. This lead to data dependency issues in my case. As a workaround I had to use locks, but a better solution would be if Dropzone events were not called from different threads in the first place.

```scala
val lock = new ReentrantLock()

dropzone.addedFileEvent.on { event =>
  lock.lock()
  try {
    // ...
  } finally {
    lock.unlock()
  }
}

dropzone.fileReceived.on { case (filename, file) =>
  lock.lock()
  try {
    // ...
  } finally {
    lock.unlock()
  }
}
```

**Comment by darkfrog26** [comment]
If I recall this is entirely dependent on JavaScript for Dropzone since both of those events come from the Dropzone.js events.  We could make a Dropzone instance use an Actor for receiving events though so that this would no longer be an issue.

**Comment by tindzk** [comment]
Using actors internally sounds reasonable. The public interface should stay the same.
